name: MedievalFactions
version: "0.3"
author: Daniel&Andrew
main: plugin.Main
api-version: "1.15"

commands:
  mf:

//  0.1 barebones project trying to get a faction class working
//  0.2 'Allow Faction Creation' update
//  0.3 'Help' update